# Generated by Django 3.2.5 on 2021-08-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210822_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='postal_code',
            field=models.CharField(max_length=8),
        ),
    ]
