# Generated by Django 3.2.5 on 2021-08-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='delivery_status',
            field=models.BooleanField(default=False),
        ),
    ]
